# Generated by Django 5.0.3 on 2024-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketoappuser',
            name='activity',
            field=models.CharField(choices=[('inactivity, sedentary work', 'Inactive'), ('low activity (sedentary work and 1-2 workouts a week)', 'Low'), ('medium activity (sedentary work and workouts 3-4 times a week)', 'Medium'), ('high activity (physical work and 3-4 workouts a week)', 'High'), ('very high activity (professional athletes, people who train every day)', 'Very High')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
