# Generated by Django 5.0.3 on 2024-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketoappuser',
            name='cmp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='daily_carbs',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='daily_fat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ketoappuser',
            name='daily_protein',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
