# Generated by Django 5.0.3 on 2024-04-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketoappuser',
            name='daily_carbs',
        ),
        migrations.RemoveField(
            model_name='ketoappuser',
            name='daily_fat',
        ),
        migrations.RemoveField(
            model_name='ketoappuser',
            name='daily_protein',
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.PositiveIntegerField(null=True)),
                ('fat', models.PositiveIntegerField(null=True)),
                ('protein', models.PositiveIntegerField(null=True)),
                ('carbs', models.PositiveIntegerField(null=True)),
                ('keto_app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ketoappuser')),
            ],
        ),
    ]
