# Generated by Django 5.0.3 on 2024-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_ketoappuser_daily_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketoappuser',
            name='activity',
            field=models.CharField(choices=[('inactive', 'inactivity, sedentary work'), ('low', 'low activity, sedentary work and 1-2 workouts a week'), ('medium', 'medium activity, sedentary work and workouts 3-4 times a week'), ('high', 'high activity, physical work and 3-4 workouts a week'), ('very_high', 'very high activity, professional athletes, people who train every day')], max_length=100, null=True),
        ),
    ]
