# Generated by Django 5.0.3 on 2024-04-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_ketoappuser_cmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='keto_app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ketoappuser'),
        ),
    ]
