# Generated by Django 5.0.3 on 2024-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_demand_keto_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketoappuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=32, null=True),
        ),
    ]
