# Generated by Django 5.0.3 on 2024-11-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_ketoappuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketoappuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=32, null=True),
        ),
    ]
