# Generated by Django 5.0.3 on 2024-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carb_in_100g', models.PositiveIntegerField()),
                ('fat_in_100g', models.PositiveIntegerField()),
                ('protein_in_100g', models.PositiveIntegerField()),
            ],
        ),
    ]
