# Generated by Django 5.0.3 on 2024-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grams',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
