# Generated by Django 5.0.3 on 2024-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_remove_product_user_product_user'),
        ('users', '0010_alter_demand_keto_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(to='users.ketoappuser'),
        ),
    ]
