# Generated by Django 5.0.3 on 2024-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_fulldayintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulldayintake',
            name='products',
        ),
        migrations.AddField(
            model_name='fulldayintake',
            name='product',
            field=models.ManyToManyField(to='calculator.product'),
        ),
    ]
