# Generated by Django 5.0.3 on 2024-04-28 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_fulldayintake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldayintake',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 28, 12, 24, 38, 643483)),
        ),
    ]
