# Generated by Django 5.0.3 on 2024-04-28 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_alter_fulldayintake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldayintake',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 4, 28)),
        ),
    ]
