# Generated by Django 5.0.3 on 2024-05-14 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldayintake',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
