# Generated by Django 5.0.3 on 2024-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_alter_fulldayintake_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulldayintake',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulldayintake',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
