# Generated by Django 5.0.3 on 2024-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_fulldayintake_end_fulldayintake_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldayintake',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulldayintake',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
