# Generated by Django 5.0.3 on 2024-06-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_alter_fulldayintake_end_alter_fulldayintake_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulldayintake',
            name='end',
        ),
    ]
