# Generated by Django 5.0.3 on 2024-12-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_alter_product_grams'),
        ('users', '0012_alter_ketoappuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulldayintake',
            name='user',
        ),
        migrations.AddField(
            model_name='fulldayintake',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ketoappuser'),
        ),
    ]
