# Generated by Django 5.0.3 on 2025-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0022_remove_fulldayintake_user_fulldayintake_user'),
        ('users', '0012_alter_ketoappuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(related_name='products', to='users.ketoappuser'),
        ),
    ]
