# Generated by Django 5.0.3 on 2025-01-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_alter_product_user'),
        ('users', '0012_alter_ketoappuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldayintake',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ketoappuser'),
        ),
    ]
